// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsKsPlayerApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashKsPlayerApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsKsPlayerApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsKsPlayerApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsKsPlayerApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsKsPlayerApi(lhsKey, rhsKey) {
          if deepEqualsKsPlayerApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsKsPlayerApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashKsPlayerApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashKsPlayerApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashKsPlayerApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashKsPlayerApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashKsPlayerApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashKsPlayerApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum KsPlayerEventType: Int {
  case ready = 0
  case playing = 1
  case buffering = 2
  case position = 3
  case duration = 4
  case size = 5
  case completed = 6
  case error = 7
  case firstFrame = 8
  case pictureInPicture = 9
}

/// Generated class from Pigeon that represents data sent in messages.
struct KsPlayerEvent: Hashable {
  var playerId: Int64
  var type: KsPlayerEventType
  var boolValue: Bool? = nil
  var numberValue: Double? = nil
  var secondaryNumberValue: Double? = nil
  var stringValue: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KsPlayerEvent? {
    let playerId = pigeonVar_list[0] as! Int64
    let type = pigeonVar_list[1] as! KsPlayerEventType
    let boolValue: Bool? = nilOrValue(pigeonVar_list[2])
    let numberValue: Double? = nilOrValue(pigeonVar_list[3])
    let secondaryNumberValue: Double? = nilOrValue(pigeonVar_list[4])
    let stringValue: String? = nilOrValue(pigeonVar_list[5])

    return KsPlayerEvent(
      playerId: playerId,
      type: type,
      boolValue: boolValue,
      numberValue: numberValue,
      secondaryNumberValue: secondaryNumberValue,
      stringValue: stringValue
    )
  }
  func toList() -> [Any?] {
    return [
      playerId,
      type,
      boolValue,
      numberValue,
      secondaryNumberValue,
      stringValue,
    ]
  }
  static func == (lhs: KsPlayerEvent, rhs: KsPlayerEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsKsPlayerApi(lhs.playerId, rhs.playerId) && deepEqualsKsPlayerApi(lhs.type, rhs.type) && deepEqualsKsPlayerApi(lhs.boolValue, rhs.boolValue) && deepEqualsKsPlayerApi(lhs.numberValue, rhs.numberValue) && deepEqualsKsPlayerApi(lhs.secondaryNumberValue, rhs.secondaryNumberValue) && deepEqualsKsPlayerApi(lhs.stringValue, rhs.stringValue)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KsPlayerEvent")
    deepHashKsPlayerApi(value: playerId, hasher: &hasher)
    deepHashKsPlayerApi(value: type, hasher: &hasher)
    deepHashKsPlayerApi(value: boolValue, hasher: &hasher)
    deepHashKsPlayerApi(value: numberValue, hasher: &hasher)
    deepHashKsPlayerApi(value: secondaryNumberValue, hasher: &hasher)
    deepHashKsPlayerApi(value: stringValue, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct KsPlayerAudioTrack: Hashable {
  var id: String
  var title: String
  var language: String
  var selected: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> KsPlayerAudioTrack? {
    let id = pigeonVar_list[0] as! String
    let title = pigeonVar_list[1] as! String
    let language = pigeonVar_list[2] as! String
    let selected = pigeonVar_list[3] as! Bool

    return KsPlayerAudioTrack(
      id: id,
      title: title,
      language: language,
      selected: selected
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      title,
      language,
      selected,
    ]
  }
  static func == (lhs: KsPlayerAudioTrack, rhs: KsPlayerAudioTrack) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsKsPlayerApi(lhs.id, rhs.id) && deepEqualsKsPlayerApi(lhs.title, rhs.title) && deepEqualsKsPlayerApi(lhs.language, rhs.language) && deepEqualsKsPlayerApi(lhs.selected, rhs.selected)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("KsPlayerAudioTrack")
    deepHashKsPlayerApi(value: id, hasher: &hasher)
    deepHashKsPlayerApi(value: title, hasher: &hasher)
    deepHashKsPlayerApi(value: language, hasher: &hasher)
    deepHashKsPlayerApi(value: selected, hasher: &hasher)
  }
}

private class KsPlayerApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KsPlayerEventType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return KsPlayerEvent.fromList(self.readValue() as! [Any?])
    case 131:
      return KsPlayerAudioTrack.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class KsPlayerApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? KsPlayerEventType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? KsPlayerEvent {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? KsPlayerAudioTrack {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class KsPlayerApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return KsPlayerApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return KsPlayerApiPigeonCodecWriter(data: data)
  }
}

class KsPlayerApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = KsPlayerApiPigeonCodec(readerWriter: KsPlayerApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol OmmKsPlayerHostApi {
  func create(playerId: Int64) throws
  func open(playerId: Int64, url: String, startPositionMs: Double?, autoplay: Bool, headers: [String: String]?, formatHint: String?, videoCodec: String?, preloadBytes: Int64?, hardwareAcceleration: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  func play(playerId: Int64) throws
  func pause(playerId: Int64) throws
  func stop(playerId: Int64) throws
  func seek(playerId: Int64, positionMs: Double, completion: @escaping (Result<Void, Error>) -> Void)
  func setRate(playerId: Int64, rate: Double) throws
  func audioTracks(playerId: Int64, completion: @escaping (Result<[KsPlayerAudioTrack], Error>) -> Void)
  func selectAudioTrack(playerId: Int64, trackId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func selectSubtitleTrack(playerId: Int64, trackId: String, fallbackIndex: Int64?, completion: @escaping (Result<Void, Error>) -> Void)
  func clearSubtitleTrack(playerId: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func captureFrame(playerId: Int64, positionMs: Double, completion: @escaping (Result<FlutterStandardTypedData?, Error>) -> Void)
  func cancelFramePreview(playerId: Int64) throws
  func startPictureInPicture(playerId: Int64, completion: @escaping (Result<Bool, Error>) -> Void)
  func stopPictureInPicture(playerId: Int64) throws
  func dispose(playerId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class OmmKsPlayerHostApiSetup {
  static var codec: FlutterStandardMessageCodec { KsPlayerApiPigeonCodec.shared }
  /// Sets up an instance of `OmmKsPlayerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: OmmKsPlayerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let createChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omm_ksplayer.OmmKsPlayerHostApi.create\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          try api.create(playerId: playerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createChannel.setMessageHandler(nil)
    }
    let openChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omm_ksplayer.OmmKsPlayerHostApi.open\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let urlArg = args[1] as! String
        let startPositionMsArg: Double? = nilOrValue(args[2])
        let autoplayArg = args[3] as! Bool
        let headersArg: [String: String]? = nilOrValue(args[4])
        let formatHintArg: String? = nilOrValue(args[5])
        let videoCodecArg: String? = nilOrValue(args[6])
        let preloadBytesArg: Int64? = nilOrValue(args[7])
        let hardwareAccelerationArg = args[8] as! Bool
        api.open(playerId: playerIdArg, url: urlArg, startPositionMs: startPositionMsArg, autoplay: autoplayArg, headers: headersArg, formatHint: formatHintArg, videoCodec: videoCodecArg, preloadBytes: preloadBytesArg, hardwareAcceleration: hardwareAccelerationArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openChannel.setMessageHandler(nil)
    }
    let playChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omm_ksplayer.OmmKsPlayerHostApi.play\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          try api.play(playerId: playerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playChannel.setMessageHandler(nil)
    }
    let pauseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omm_ksplayer.OmmKsPlayerHostApi.pause\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          try api.pause(playerId: playerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseChannel.setMessageHandler(nil)
    }
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omm_ksplayer.OmmKsPlayerHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          try api.stop(playerId: playerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    let seekChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omm_ksplayer.OmmKsPlayerHostApi.seek\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      seekChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let positionMsArg = args[1] as! Double
        api.seek(playerId: playerIdArg, positionMs: positionMsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      seekChannel.setMessageHandler(nil)
    }
    let setRateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omm_ksplayer.OmmKsPlayerHostApi.setRate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setRateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let rateArg = args[1] as! Double
        do {
          try api.setRate(playerId: playerIdArg, rate: rateArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setRateChannel.setMessageHandler(nil)
    }
    let audioTracksChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omm_ksplayer.OmmKsPlayerHostApi.audioTracks\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      audioTracksChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        api.audioTracks(playerId: playerIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      audioTracksChannel.setMessageHandler(nil)
    }
    let selectAudioTrackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omm_ksplayer.OmmKsPlayerHostApi.selectAudioTrack\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      selectAudioTrackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let trackIdArg = args[1] as! String
        api.selectAudioTrack(playerId: playerIdArg, trackId: trackIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      selectAudioTrackChannel.setMessageHandler(nil)
    }
    let selectSubtitleTrackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omm_ksplayer.OmmKsPlayerHostApi.selectSubtitleTrack\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      selectSubtitleTrackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let trackIdArg = args[1] as! String
        let fallbackIndexArg: Int64? = nilOrValue(args[2])
        api.selectSubtitleTrack(playerId: playerIdArg, trackId: trackIdArg, fallbackIndex: fallbackIndexArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      selectSubtitleTrackChannel.setMessageHandler(nil)
    }
    let clearSubtitleTrackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omm_ksplayer.OmmKsPlayerHostApi.clearSubtitleTrack\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearSubtitleTrackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        api.clearSubtitleTrack(playerId: playerIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearSubtitleTrackChannel.setMessageHandler(nil)
    }
    let captureFrameChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omm_ksplayer.OmmKsPlayerHostApi.captureFrame\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      captureFrameChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        let positionMsArg = args[1] as! Double
        api.captureFrame(playerId: playerIdArg, positionMs: positionMsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      captureFrameChannel.setMessageHandler(nil)
    }
    let cancelFramePreviewChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omm_ksplayer.OmmKsPlayerHostApi.cancelFramePreview\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelFramePreviewChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          try api.cancelFramePreview(playerId: playerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelFramePreviewChannel.setMessageHandler(nil)
    }
    let startPictureInPictureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omm_ksplayer.OmmKsPlayerHostApi.startPictureInPicture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startPictureInPictureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        api.startPictureInPicture(playerId: playerIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startPictureInPictureChannel.setMessageHandler(nil)
    }
    let stopPictureInPictureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omm_ksplayer.OmmKsPlayerHostApi.stopPictureInPicture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopPictureInPictureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          try api.stopPictureInPicture(playerId: playerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopPictureInPictureChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omm_ksplayer.OmmKsPlayerHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! Int64
        do {
          try api.dispose(playerId: playerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol OmmKsPlayerFlutterApiProtocol {
  func onEvent(event eventArg: KsPlayerEvent, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class OmmKsPlayerFlutterApi: OmmKsPlayerFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: KsPlayerApiPigeonCodec {
    return KsPlayerApiPigeonCodec.shared
  }
  func onEvent(event eventArg: KsPlayerEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.omm_ksplayer.OmmKsPlayerFlutterApi.onEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
